prompt_sets:
  default:
    map_prompt: "prompts/map_prompt_hybrid.yml"
    reduce_prompt: "prompts/reduce_prompt_hybrid.yml"
    judge_prompt: "prompts/judge_prompt.yml"

  baseline:
    map_prompt: "prompts/map_prompt_baseline.yml"
    reduce_prompt: "prompts/reduce_prompt_baseline.yml"
    judge_prompt: "prompts/judge_prompt_baseline.yml"

  standard:
    map_prompt: "prompts/map_prompt.yml"
    reduce_prompt: "prompts/reduce_prompt.yml"
    judge_prompt: "prompts/judge_prompt.yml"

  hybrid:
    map_prompt: "prompts/map_prompt_hybrid.yml"
    reduce_prompt: "prompts/reduce_prompt_hybrid.yml"
    judge_prompt: "prompts/judge_prompt.yml"
    question_improvement_prompt: "prompts/question_improvement_prompt.yml"

  direct:
    map_prompt: "prompts/direct_prompt.yml"
    reduce_prompt: "prompts/direct_prompt.yml"
    judge_prompt: "prompts/judge_prompt.yml"

  finqa:
    map_prompt: "prompts/map_prompt_finqa.yml"
    reduce_prompt: "prompts/reduce_prompt_finqa.yml"
    judge_prompt: "prompts/judge_prompt.yml"

# Default prompt set if none specified
default_set: "default"